apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-new-claim
  labels:
    app: elasticsearch-kibana
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch-kibana
  labels:
    app: elasticsearch-kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch-kibana
  template:
    metadata:
      labels:
        app: elasticsearch-kibana
    spec:
      initContainers:
      - name: set-vm-max-map-count
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ['sysctl', '-w', 'vm.max_map_count=262144']
        securityContext:
          privileged: true
      containers:
      - name: elasticsearch-kibana
        image: sebp/elk
        resources:
          limits:
            memory: 3Gi
            cpu: "2"
          requests:
            memory: 512Mi
            cpu: "250m"
        ports:
        - containerPort: 5601
        - containerPort: 9200
        env:
        - name: MSSQL_PID
          value: "Developer"
        volumeMounts:
        - name: elasticsearch-persistent-storage
          mountPath: /var/lib/elasticsearch
      volumes:
      - name: elasticsearch-persistent-storage
        persistentVolumeClaim:
          claimName: elasticsearch-new-claim
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
spec:
  ports:
  - port: 9200
    targetPort: 9200
  selector:
    app: elasticsearch-kibana
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: kibana
spec:
  ports:
  - port: 5601
    targetPort: 5601
  selector:
    app: elasticsearch-kibana
  type: LoadBalancer